version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bootcamp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bootcamp
      POSTGRES_PASSWORD: bootcamp
      POSTGRES_DB: bootcamp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: